# Generated by Django 4.1.2 on 2022-10-29 03:40

from django.db import migrations, models
import django.db.models.deletion
import tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('rpc_url', models.URLField()),
                ('chain_id', models.PositiveIntegerField()),
                ('currency_symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('block_explorer', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code_name', models.CharField(max_length=10)),
                ('contract_address', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=tracker.models.Token.img_logo_path)),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.network')),
            ],
        ),
        migrations.CreateModel(
            name='SupplySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supply', models.DecimalField(decimal_places=4, max_digits=32)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_data', to='tracker.token')),
            ],
        ),
    ]
