# Generated by Django 4.1.2 on 2022-10-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='decimals',
            field=models.IntegerField(default=18),
        ),
    ]
